Add transform model
w3c/webrtc-insertable-streams pull request #51
Opened 2021-01-21 11:23 UTC by youennf

2021-01-21 11:26 UTC, youennf commented
@guidou @alvestrand @henbos @jan-ivar, I uploaded a first version that outlines the overall direction and defines the base algorithms that we discussed during the past interims.
This needs further polishing, at least in terms of style, but I prefer getting your input first before taking more time on purely editorial work.

2021-01-26 17:31 UTC, youennf commented
I added the skeleton for RTCRtpScriptTransform as well on window side.
I think it is ready for functional review.
I am particularly interested in hearing about the following points:
- Ability to change @transform on the fly
- Ability to not miss any frame if @transform is set synchronously at creation time of the sender/receiver
- Validation of the use of the streams API and related algorithms

2021-01-28 16:02 UTC, youennf commented
@ricea, @domenic, I am wondering if you have feedback on the use of ReadableStream/WritableStream constructs in this PR.

2021-01-29 05:27 UTC, ricea reviewed
I don't fully understand the webrtc parts, but I think it looks okay.

2021-01-29 05:27 UTC, ricea commented on index.bs
> +3. Initialize `[[readable]]` to the result of <a href="https://streams.spec.whatwg.org/#readablestream-create">creating a</a> {{ReadableStream}}. `[[readable]]` is provided frames using the [=readEnc
I think `<a dfn for="ReadableStream">creating</a> a` will work, and will allow Bikeshed to include it in the "Terms defined by reference" section. Also below.

2021-01-29 08:43 UTC, youennf commented on index.bs
> +3. Initialize `[[readable]]` to the result of <a href="https://streams.spec.whatwg.org/#readablestream-create">creating a</a> {{ReadableStream}}. `[[readable]]` is provided frames using the [=readEnc
Thanks, I updated two links. I think there is further improvements that could be done but I am not very familiar with how to do it.
For instance referring to 'pipeTo' , abort signal...

2021-01-29 21:16 UTC, domenic reviewed
Since you seemed interested in better Bikeshed and spec-phrasing tips, I gave a bunch of suggestions :)

2021-01-29 21:16 UTC, domenic commented on index.bs
> +5. Initialize `[[writable]]` to the result of <a dfn for="WritableStream">creating</a> a {{WritableStream}}, its <a href="https://streams.spec.whatwg.org/#writablestream-create-writealgorithm">writeA
```suggestion
5. Initialize `[[writable]]` to the result of [=WritableStream/creating=] a {{WritableStream}}, its [=WritableStream/create/writeAlgorithm=] set to [=writeEncodedData=] given |this| as parameter.
```

Note that the "given |this| as parameter" is kind of a workaround for a Streams spec issue: https://github.com/whatwg/streams/issues/1084

2021-01-29 21:16 UTC, domenic commented on index.bs
> +    2. Call <a href="https://streams.spec.whatwg.org/#readable-stream-pipe-to">pipeTo</a> with `[[readable]]`, `[[writable]]`, preventClose equal to true, preventAbort equal to true, preventCancel eq
You should not call public API methods, but we haven't made this easy for you. I will work on an algorithm your spec can call.

2021-01-29 21:16 UTC, domenic commented on index.bs
> +2. If the data source does not permit access, throw an {{InvalidAccessError}} and abort these steps.
```suggestion
2. If the data source does not permit access, throw an "{{InvalidAccessError}}" {{DOMException}} and abort these steps.
```

here and elsewhere (per https://heycam.github.io/webidl/#idl-exceptions)

2021-01-29 21:16 UTC, domenic commented on index.bs
> +4. <a href="https://streams.spec.whatwg.org/#readablestream-enqueue">Enqueue</a> |frame| in |rtcObject|.`[[readable]]`.
```suggestion
4. [=ReadableStream/enqueue=] |frame| in |rtcObject|.`[[readable]]`.
```

2021-01-29 21:16 UTC, domenic commented on index.bs
> +1. Initialize `[[Streams]]` to null.
Here and elsewhere, I suggest using `[=this=].\[[Streams]]` or `` [=this=].`[[Streams]]` ``

2021-01-29 21:16 UTC, domenic commented on index.bs
>  called, run the following steps:
```suggestion
The <dfn method for="RTCRtpSender">createEncodedStreams()</dfn> method steps are:
```

2021-01-29 21:16 UTC, domenic commented on index.bs
> +On getting the transform attribute, the user agent MUST run the following steps:
```suggestion
The <dfn attribute for="RTCRtpSender,RTCRtpReceiver">transform</dfn> getter steps are:
```

2021-01-29 21:16 UTC, domenic commented on index.bs
> +On setting the transform attribute, the user agent MUST run the following steps:
```suggestion
The `transform` setter steps are:
```

2021-01-29 21:16 UTC, domenic commented on index.bs
> +2. Return |rtcObject|.`[[transform]]`.
```suggestion
1. Return [=this=].`[[transform]]`.
```

2021-01-29 21:16 UTC, domenic commented on index.bs
> +1. Let |rtcObject| be the {{RTCRtpReceiver}} or {{RTCRtpSender}} on which the setter is invoked.
As above, eliminate this variable and just use `[=this=]`

2021-01-29 21:16 UTC, domenic commented on index.bs
> +3. Let |checkedTransform| set to |transform| if it is not null or to an <a href="https://streams.spec.whatwg.org/#identity-transform-stream">identity transform</a> otherwise.
```suggestion
3. Let |checkedTransform| set to |transform| if it is not null or to the result of [=creating an identity TransformStream=] otherwise.
```

2021-01-29 21:16 UTC, domenic commented on index.bs
> +3. Let |reader| be the result of <a href="https://streams.spec.whatwg.org/#readablestream-get-a-reader">getting a reader</a> for |checkedTransform|.`[[readable]]`.
```suggestion
3. Let |reader| be the result of [=ReadableStream/getting a reader=] for |checkedTransform|.`[[readable]]`.
```

2021-01-29 21:16 UTC, domenic commented on index.bs
> +4. Let |writer| be the result of <a href="https://streams.spec.whatwg.org/#writablestream-get-a-writer">getting a writer</a> for |checkedTransform|.`[[writable]]`.
```suggestion
4. Let |writer| be the result of [=WritableStream/getting a writer=] for |checkedTransform|.`[[writable]]`.
```

2021-01-29 21:16 UTC, domenic commented on index.bs
> +5. Initialize |newPipeToController| to a new AbortController.
```suggestion
5. Let |newPipeToController| be a new {{AbortController}}.
```

2021-01-29 21:16 UTC, domenic commented on index.bs
> +    1. <a href="https://dom.spec.whatwg.org/#abortsignal-add">Add</a> the [=chain transform algorithm=] to |rtcObject|.`[[pipeToController]]`:
```suggestion
    1. [=AbortSignal/add=] the [=chain transform algorithm=] to |rtcObject|.`[[pipeToController]]`'s [=AbortController/signal=]:
```

2021-01-29 21:16 UTC, domenic commented on index.bs
> +    2. Call <a href="https://dom.spec.whatwg.org/#abortsignal-signal-abort">abort</a> on |rtcObject|.`[[pipeToController]]`.
```suggestion
    2. [=AbortSignal/Signal abort=] on |rtcObject|.`[[pipeToController]]`'s [=AbortController/signal=].
```

2021-01-29 21:16 UTC, domenic commented on index.bs
> +1. If |newPipeToController| <a href="https://dom.spec.whatwg.org/#abortsignal-aborted-flag">aborted flag</a> is true, abort these steps.
```suggestion
1. If |newPipeToController|'s [=AbortController/signal=]'s [=AbortSignal/aborted flag=] is true, return.
```

2021-01-29 21:16 UTC, domenic commented on index.bs
> +2. Call <a href="https://streams.spec.whatwg.org/#readablestreamdefaultreader-release">release</a> with |reader|.
```suggestion
2. [=ReadableStreamDefaultReader/Release=] |reader|.
```

2021-01-29 21:16 UTC, domenic commented on index.bs
> +3. Call <a href="https://streams.spec.whatwg.org/#writablestreamdefaultwriter-release">release</a> with |writer|.
```suggestion
3. [=WritableStreamDefaultWriter/Release=] |writer|.
```

2021-01-29 21:16 UTC, domenic commented on index.bs
> +When the SFrameTransform.constructor() is invoked, run the following steps:
```suggestion
The <dfn constructor for="SFrameTransform" lt="SFrameTransform(options)"><code>new SFrameTransform(<var>options</var>)</code></dfn> constructor steps are:
```

2021-01-29 21:16 UTC, domenic commented on index.bs
> +2. Set |this|.<a href="https://streams.spec.whatwg.org/#generictransformstream-transform">`[[transform]]`</a> to the result of <a href="https://streams.spec.whatwg.org/#transformstream-create">creati
```suggestion
2. Set |this|.<a href="https://streams.spec.whatwg.org/#generictransformstream-transform">`[[transform]]`</a> to the result of [=TransformStream/creating=] a {{TransformStream}}, with [=TransformStream/create/transformAlgorithm=] set to |transformAlgorithm|.
```

2021-01-29 21:16 UTC, domenic commented on index.bs
> +4. Set |this|.`[[role]]` to |options|.role.
```suggestion
4. Set |this|.`[[role]]` to |options|["{{SFrameTransportOptions/role}}"].
```

2021-01-29 21:16 UTC, domenic commented on index.bs
> +When the RTCRtpScriptTransform.constructor() is invoked, run the following steps:
```suggestion
The <dfn constructor for="RTCRtpScriptTransform" lt="RTCRtpScriptTransform(worker, options)"><code>new RTCRtpScriptTransform(<var>worker</var>, <var>options</var>)</code></dfn> constructor steps are:
```

2021-01-29 23:37 UTC, jan-ivar requested changes

2021-01-29 23:47 UTC, jan-ivar commented on index.bs
> +4. <a href="https://streams.spec.whatwg.org/#readablestream-enqueue">Enqueue</a> |frame| in |rtcObject|.`[[readable]]`.
Wait, that's not right. 🤦‍♂️ How about `readEncoderFrame` and `readPacketizerFrame`?

2021-01-29 23:50 UTC, jan-ivar commented on index.bs
> +    * If |rtcObject| is a {{RTCRtpReceiver}}, enqueue it to |rtcObject|'s decoder.
`writePacketizerFrame` and `writeDecoderFrame`?

2021-01-29 23:55 UTC, jan-ivar commented on index.bs
> +4. <a href="https://streams.spec.whatwg.org/#readablestream-enqueue">Enqueue</a> |frame| in |rtcObject|.`[[readable]]`.
On third thought, ignore me here, since the algorithms overlap so well otherwise.

2021-02-01 10:01 UTC, youennf commented
> Since you seemed interested in better Bikeshed and spec-phrasing tips, I gave a bunch of suggestions :)

Thanks, this is greatly appreciated!

2021-02-01 10:07 UTC, youennf commented on index.bs
> +    constructor(any worker, optional object options); // worker as DedicatedWorker.
Right, I wanted to verify we were not allowing constructing a transform on a shared worker, hence the ref to DedicatedWorker. Your proposed fix is good.

2021-02-01 10:08 UTC, youennf commented on index.bs
> +2. If the data source does not permit access, throw an {{InvalidAccessError}} and abort these steps.
Will go through the doc and fix this.

2021-02-01 10:43 UTC, youennf commented on index.bs
> +    2. Call <a href="https://streams.spec.whatwg.org/#readable-stream-pipe-to">pipeTo</a> with `[[readable]]`, `[[writable]]`, preventClose equal to true, preventAbort equal to true, preventCancel eq
Fixed in latest commit

2021-02-01 10:44 UTC, youennf commented on index.bs
> +1. Initialize `[[Streams]]` to null.
Done

2021-02-01 10:47 UTC, youennf commented on index.bs
> +    2. Call <a href="https://streams.spec.whatwg.org/#readable-stream-pipe-to">pipeTo</a> with `[[readable]]`, `[[writable]]`, preventClose equal to true, preventAbort equal to true, preventCancel eq
Added a FIXME for now.

2021-02-01 11:00 UTC, youennf commented on index.bs
> +1. Let |rtcObject| be the {{RTCRtpReceiver}} or {{RTCRtpSender}} on which the setter is invoked.
Done

2021-02-01 13:54 UTC, guidou commented on index.bs
> +3. Initialize [=this=].`[[readable]]` to the result of <a dfn for="ReadableStream">creating</a> a {{ReadableStream}}. `[[readable]]` is provided frames using the [=readEncodedData=] algorithm given |
Should this be done only when RTCConfiguration.encodedInsertableStreams is true?

2021-02-01 13:55 UTC, guidou commented on index.bs
> +    1. If [=this=].`[[pipeToController]]` is not null, abort these steps.
Can it be null at this point?

2021-02-01 14:12 UTC, youennf commented on index.bs
> +3. Initialize [=this=].`[[readable]]` to the result of <a dfn for="ReadableStream">creating</a> a {{ReadableStream}}. `[[readable]]` is provided frames using the [=readEncodedData=] algorithm given |
The algorithm applies to both cases:
- If RTCConfiguration.encodedInsertableStreams is true, readable and writable will be exposed.
- If RTCConfiguration.encodedInsertableStreams is not true, readable will be piped into writable asynchronously for the content to flow. This is not observable so an application can implement it without actually create the readable and writable slots.

2021-02-01 14:12 UTC, youennf commented on index.bs
> +    1. If [=this=].`[[pipeToController]]` is not null, abort these steps.
We enqueue a task to run this sub-step.
If transform is set before this task is run, pipeToController will no longer be null when running this task.
In that case, we abort since the transform should do the work to pipe frames from readable to writable.
If pipeToController is still null, it means that the transform was not set. In that case, we start piping frames directly from readable to writable without a transform.

This should allow us to remove the need for RTCConfiguration/encodedInsertableStreams in the 'transform' approach.

2021-02-01 15:29 UTC, jan-ivar approved these changes
Thanks for more detailed algorithms! They're helping me have questions that probably predate this patch.

So I'll approve as I approve of this detail, as well as direction, provided we open issues on anything not answered by this patch.

2021-02-01 15:29 UTC, jan-ivar commented on index.bs
> +4. Process the frame as if it came directly from the encoded data source:
"In parallel, "?

2021-02-01 15:29 UTC, jan-ivar commented on index.bs
> +The <dfn>writeEncodedData</dfn> algorithm is given a |rtcObject| as parameter and a |frame| as input. It is defined by running the following steps:
This algorithm appears set [here](https://streams.spec.whatwg.org/#set-up-writable-stream-default-controller): _"Set controller.[[[writeAlgorithm]]](https://streams.spec.whatwg.org/#writablestreamdefaultcontroller-writealgorithm) to writeAlgorithm."

...which in turn links to `WritableStreamDefaultController`, which says it's a _"A promise-returning algorithm,  taking one argument (the [chunk](https://streams.spec.whatwg.org/#chunk) to write)"_

Does that mean we need to return a promise from this algo (resolving to `undefined`)?

Also, [chunk](https://streams.spec.whatwg.org/#chunk) in turn says _"It can be of any type; streams can even contain chunks of different types."_

Do we need to do type checking here? Rejecting that promise with `TypeError` maybe?

cc @domenic in case I'm reading the spec wrong. The `WritableStreamDefaultController` language seems non-normative, and aimed a JS-based implementations, so perhaps I'm looking in the wrong place.

2021-02-01 16:35 UTC, domenic commented on index.bs
> +The <dfn>writeEncodedData</dfn> algorithm is given a |rtcObject| as parameter and a |frame| as input. It is defined by running the following steps:
Yes, good catches in both regards. You need to return a promise (resolved with undefined). And if you're receiving a chunk you don't expect, return a promise rejected with a TypeError.

https://streams.spec.whatwg.org/#other-specs-ws-creation is the entry point for other specs, but it's pretty similar:

> writeAlgorithm must be an algorithm that accepts a chunk object and returns a promise

2021-02-02 10:26 UTC, youennf commented on index.bs
> +The <dfn>writeEncodedData</dfn> algorithm is given a |rtcObject| as parameter and a |frame| as input. It is defined by running the following steps:
Oh, I guess Safari implementation should be changed then since it is wrapping writeAlgorithm (and ReadableStream calls as well) using Promise.resolve.  Did that change?
Will update the PR.

2021-02-02 10:34 UTC, youennf commented on index.bs
> +4. [=ReadableStream/enqueue=] |frame| in |rtcObject|.`[[readable]]`.
If we were to add it as steps in an algorithm, we would probably use "in parallel", like done in https://fetch.spec.whatwg.org/#http-network-fetch step 16.
There is nothing that prevents to do it in main thread, but yes, the idea is that it should be done in WebRTC data pipeline thread.

2021-02-02 10:42 UTC, youennf commented on index.bs
> +The <dfn>writeEncodedData</dfn> algorithm is given a |rtcObject| as parameter and a |frame| as input. It is defined by running the following steps:
PR updated, PTAL.

2021-02-02 10:42 UTC, youennf commented on index.bs
> +4. Process the frame as if it came directly from the encoded data source:
Done

2021-02-02 13:40 UTC, jan-ivar reviewed
Again LGTM as a start. Sorry I keep putting more comments on this PR, but this is my first review in this repo. Happy to open issues instead.

2021-02-02 13:40 UTC, jan-ivar commented on index.bs
> +5. Return [=a promise resolved with=] undefined.
Yes this looks right, in that we always want to return a promise resolved immediately to never create any delay, since we're the underlying sink, and the WritableStream would otherwise serialize data to us on the JS thread, something that would likely reduce throughput. This might be even clearer if we wrote it as:
```suggestion
4. Return [=a promise resolved with=] undefined, and process the frame as if it came directly from the encoded data source, by running the following steps [=in parallel=]:
    * If |rtcObject| is a {{RTCRtpSender}}, enqueue it to |rtcObject|'s packetizer.
    * If |rtcObject| is a {{RTCRtpReceiver}}, enqueue it to |rtcObject|'s decoder.
```
Not sure how to best write it to not appear racy though.

2021-02-02 13:40 UTC, jan-ivar commented on index.bs
> +5. Initialize [=this=].`[[writable]]` to the result of [=WritableStream/creating=] a {{WritableStream}}, its [=WritableStream/create/writeAlgorithm=] set to [=writeEncodedData=] given |this| as param
This is a good start, but we probably want more patches soon to pass in a [highWaterMark](https://streams.spec.whatwg.org/#writablestream-create-highwatermark) (of some arbitrary number?) to ensure we never exert any [backpressure](https://streams.spec.whatwg.org/#writable-stream-update-backpressure) on the insertable stream (observable by looking at `writer.ready`).

This is perhaps more an issue with the existing insertable streams API than with a pure transform, but as I understand, JS is still possible here using `RTCRtpScriptTransform` right?

2021-02-02 14:24 UTC, youennf commented on index.bs
> +5. Return [=a promise resolved with=] undefined.
I slightly prefer the original version, it seems a bit odd to do something after having returned.

2021-02-02 14:26 UTC, youennf commented on index.bs
> +5. Initialize [=this=].`[[writable]]` to the result of [=WritableStream/creating=] a {{WritableStream}}, its [=WritableStream/create/writeAlgorithm=] set to [=writeEncodedData=] given |this| as param
It depends whether we expose directly writer or not.
I agree that it might be good to further tighten this though.
A dedicated issue might be good.

2021-02-02 14:27 UTC, youennf commented
> I keep putting more comments on this PR

Keep them coming, this is useful!

> Happy to open issues instead.

I m ok with further improving this PR but it seems it is in a state where it could be merged.

2021-02-02 15:55 UTC, jan-ivar commented on index.bs
> +5. Return [=a promise resolved with=] undefined.
It's not uncommon, but here perhaps we need a safer hand-off. How about.
```suggestion
4. Enqueue the frame as if it came directly from the encoded data source, by running one of the following steps:
    * If |rtcObject| is a {{RTCRtpSender}}, enqueue it to |rtcObject|'s packetizer, to be processed [=in parallel=].
    * If |rtcObject| is a {{RTCRtpReceiver}}, enqueue it to |rtcObject|'s decoder, to be processed [=in parallel=].
5. Return [=a promise resolved with=] undefined.
```
?

2021-02-02 16:07 UTC, youennf commented on index.bs
> +5. Return [=a promise resolved with=] undefined.
Seems fine to me, let's add it!

2021-02-02 17:45 UTC, jan-ivar commented on index.bs
> +5. Initialize [=this=].`[[writable]]` to the result of [=WritableStream/creating=] a {{WritableStream}}, its [=WritableStream/create/writeAlgorithm=] set to [=writeEncodedData=] given |this| as param
Nevermind, it looks like backpressure [is released after a microtask](https://streams.spec.whatwg.org/#writable-stream-default-controller-process-write): _"Upon fulfillment of sinkWritePromise, ... Perform ! [DequeueValue](https://streams.spec.whatwg.org/#dequeue-value)(controller)."_ So since we resolve the promise immediately, that seems good enough to me to prevent pressure from ever building upstream.

2021-02-04 15:16 UTC, alvestrand commented on index.bs
> +[Exposed=(Window,DedicatedWorker)]
It would seem more structured to put the SframeTransform IDL in the Sframe section rather than in a top-level IDL section.

Similar for the script transform.

2021-02-04 16:15 UTC, guidou approved these changes

2021-02-04 16:15 UTC, merged