Add API and algorithm to expose transform to workers
w3c/webrtc-insertable-streams pull request #62
Opened 2021-02-25 12:44 UTC by youennf

2021-02-25 12:47 UTC, youennf commented
Fixes https://github.com/w3c/webrtc-insertable-streams/issues/18

2021-02-25 15:44 UTC, alvestrand requested changes
I'll have to flag this one as -1 until I figure out what it takes away.

2021-02-25 15:54 UTC, alvestrand commented
Suggest making one PR to add the new API and another one that takes the old API away, so that we can discuss them separately.

2021-02-26 17:03 UTC, youennf commented
> uggest making one PR to add the new API and another one that takes the old API away, so that we can discuss them separately.

I reverted the changes, PR now only adds stuff!

2021-03-04 12:08 UTC, alvestrand approved these changes
Now that "removing the old way" is removed, this is a completion of the algorithm already landed, and I approve.

I do wonder if we can get the ability to "polyfill" the old behavior by allowing the "worker" argument to the ScriptTransform constructor to be the Javascript equivalent of "this" - that would make same-process processing possible, but not simpler than worker-based processing.

2021-03-04 12:08 UTC, alvestrand commented on index.bs
> +6. Let |serializedReadable| be the result of [$StructuredSerializeWithTransfer$](|t1|.`[[readable]]`, « |t1|.`[[readable]]` »).
Should the << marks be square brackets? (I think the second argument to Serialize is a transfer list)

2021-03-04 12:11 UTC, alvestrand commented
Note: I'd be even happier if the PR also added examples to explainer.md.

2021-03-04 12:13 UTC, youennf commented on index.bs
> +6. Let |serializedReadable| be the result of [$StructuredSerializeWithTransfer$](|t1|.`[[readable]]`, « |t1|.`[[readable]]` »).
Not sure what style is best here.
I reused the style used in https://streams.spec.whatwg.org/#ws-transfer.

2021-03-04 12:14 UTC, youennf commented
> Note: I'd be even happier if the PR also added examples to explainer.md.

I agree we should do that before landing https://github.com/w3c/webrtc-insertable-streams/pull/64.

2021-03-04 13:51 UTC, alvestrand commented
Thinking some more - in all cases the transform object is created on the main thread (constructor has exposed=window).
If "worker" argument is nullable, we can say "no event is fired when worker is null", and we have a very reasonably shimmable interface that gives us the old functionality. WDYT?

2021-03-04 14:20 UTC, alvestrand commented
Note: DedicatedWorker is still a link that goes nowhere.

2021-03-04 14:27 UTC, guidou commented
Some examples of how the API is intended to be used in practice would be very beneficial to be able to figure out a plan to implement it. I would prefer that we keep the old API in the spec until implementors have had time to evaluate the new one in practical settings.

2021-03-04 14:28 UTC, alvestrand commented on index.bs
> +interface RTCRtpScriptTransformer {
After having tried to comprehend the overall algorithm several times, I've concluded that we should rename this object to RTCRtpScriptTransformSocket. It's not a transformer itself, it's what you plug a transform (like SframeTransform) into.

2021-03-04 14:28 UTC, alvestrand commented on index.bs
>  interface RTCRtpScriptTransform {
similarly, RTCRtpScriptTransform is not a transform. I suggest we call it RTCRtpScriptTransformController.

2021-03-04 15:22 UTC, alvestrand commented
New issues:
- Add examples
- Work on naming (align with stream spec, such as DuplexStream and Endpoint Pair)
-

2021-03-04 15:22 UTC, merged

2021-03-08 09:35 UTC, foolip commented on index.bs
> +partial interface DedicatedWorkerGlobalScope : WorkerGlobalScope {
With partial interfaces in Web IDL the parent interface shouldn't be specified. I've sent https://github.com/w3c/webrtc-insertable-streams/pull/71 to fix this.

2021-03-08 09:59 UTC, foolip commented on index.bs
> +partial interface DedicatedWorkerGlobalScope : WorkerGlobalScope {
Fixed in https://github.com/w3c/webrtc-insertable-streams/pull/70.

2021-03-08 10:00 UTC, foolip commented on index.bs
> -dictionary RTCInsertableStreams {
The `RTCInsertableStreams` dictionary was removed here, but it's still used as the return type of two methods in https://w3c.github.io/webrtc-insertable-streams/#specification.

2021-03-08 10:02 UTC, youennf commented on index.bs
> -dictionary RTCInsertableStreams {
Oh, that is a mistake from splitting  the PR, I will add it back.

2021-03-08 10:07 UTC, youennf commented on index.bs
> -dictionary RTCInsertableStreams {
https://github.com/w3c/webrtc-insertable-streams/pull/73